site_name: 我的 Lean 学习笔记
site_author: hewzhew

nav:
      - 首页: index.md
      - 建站经验: website-setup-faq.md
      - Lean:
          - Lean 搜索:
              - lean/search/precise-search.md
          - Lean 工具:
              - lean/tools/lean-tools.md
theme:
  name: material
  language: zh
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: 切换到暗色模式
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: 切换到亮色模式
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.annotate
    - content.code.copy
    - tags

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - attr_list

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.jss